name: build_master

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Run build
      - name: build_script
        working-directory: $GITHUB_WORKSPACE
        run: |
          ./ci_build.sh

